### ISSUE TITLE
[EPIC] Интеграция с IOT

### ISSUE THREAD

**Issue by qertis** [gotois/ProstoDiary_bot#11]
Идея: брать данные со связанных устройство, чтобы данные о пользовательском дне вводились автоматически. 
* Просыпаюсь (Jawbone)
* Начинаю чистить зубы (OralB API?)
* Открываю холодильник (Умный холодильник API?)
* Засыпаю (Jawbone)

**Comment by qertis** [comment]
Создал приложение https://jawbone.com/up/developer/apps/JDm1g2HwDNw

**Comment by baskovsky** [comment]
https://www.npmjs.com/package/passport-jawbone

**Comment by baskovsky** [comment]
Нужен сервак для обработки OAuth2. Сейчас это gotointeractive.com, что неправильно. Нужно переделать под Heroku там же, где хостится ProstoDiary bot

**Comment by qertis** [comment]
Нет, нужно просто брать token и переносить в ENV

**Comment by qertis** [comment]
Браслеты уже не оч. Возможно стоит задуматься об внедрении API iPhone Health. Но это не точно.

**Comment by qertis** [comment]
Особенно интересна штука с очками, если будет возможность прямиком загружать в бота фотки еды - тогда можно построить на этом автоматический сбор статистики по приему еды / учет калорий и времени еды

**Comment by qertis** [comment]
записывать человеческие характеристики: что человек видит, что слышит, его температура тела, передвижение пользователя по миру. 

По этим данным можно обучать систему выявлять самые ненужные и бесполезные задачи. В теории система благодаря этим данным сама за пользователя будет совершать покупки, планировать его отдых, организовывать встречи с людьми (порой даже незнакомыми). 

Вместо долгого раздумывания куда сходить, есть ли на это время, хватит ли на это финансов, смогу ли я найти что-то полезное для себя, Q благодаря эффекту масштаба и обзора множества данных о пользователях сможет гораздо полезнее планировать их жизнь. Стать скорее наставником, нежели простым помощником. На основе лучших пользовательских качеств формируя ему лучшую жизнь, которую он только может получить.

**Comment by qertis** [comment]
Более любопытная идея.

Использовать ботов как способ управления вещами.

**Comment by qertis** [comment]
Предоставить боту возможность считывать бессознательное своего пользователя. 
Предоставить боту, на основе этих данных, управлять разрешенными девайсами во благо пользователя.
В дальнейшем боты должны сами организовать неуправляемую внешне сферу.
В этой сфере импульсами должны стать бессознательное всех людей. 
Любые данные в сфере должны предстать черным ящиком - для обеспечения индивидуальной свободы каждого пользователя.
Система должна замкнуться. 
Любое внешнее вмешательство должно игнорироваться, откатываясь до состояния, когда вмешательства не было.

**Comment by qertis** [comment]
Решение бытовых вопросов IOT
---
уборка
доставка
сантехник
слесарь
записи к врачам
услуги охраны и телохранителей
-> все это будет решаться через /task, потом автоматически

**Comment by qertis** [comment]
По этому поводу решил следующим образом:
На каждое новое IOT устройство копируется ссылка бота, которая смотрит только на то, что это устройство делает. Бот анализирует трафик от устройства и записывает его в общее хранилище бота.

**Comment by qertis** [comment]
Получается два действия бота:
1 - Копирование ссылки себя на устройство и доступ только на запись
2 - Перемещение самого бота в ближайшее устройство своего пользователя и возможность чтения

**Comment by qertis** [comment]
перенос в проекты https://github.com/orgs/gotois/projects/
